development:
  adapter: postgresql
  database: spellhelper_development
  min_messages: WARNING

test:
  adapter: postgresql
  database: spellhelper_test
  min_messages: WARNING

production:
  adapter: postgresql
  database: spellhelper_development
  min_messages: WARNING
